blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('news/',views.all_news,name ='all_news'),
    path('search/', views.search, name='search'),
    path('',views.index,name='index'),
    path('contact-us/',views.contact_us,name='contact_us'),
    path('about/',views.about,name='about'),
    path('<slug:slug>/',views.news_detail,name='news_detail'),
    
]

myrahkar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('mjs/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('startup-and-courses/',include('startup.urls'),name='startup'),
    path('',include('blog.urls'),name = 'blog'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startup/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='startup'

urlpatterns = [
    path('articles/',views.all_article,name ='all_article'),
    path('courses/',views.courses_index,name='courses_index'),
    path('startup/',views.startup_index,name='startup_index'),
    path('course_register/',views.course_register,name='course_register'),
    path('startup_register/',views.startup_register,name='startup_register'),
    path('<slug:slug>/',views.article_detail,name='article_detail'),
]

startup/models.py
from django.db import models
from django_jalali.db import models as jmodels
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

CHOICES = [
    ('u','دانشجو'),
    ('g','فارغ التحصیل'),
    ('s','دانش آموز'),
    ('n','هیچکدام')
]
CHOICES_IDEA = [
    ('r','ثبت شده'),
    ('n','ثبت نشده '),
    ('q','غیره')
]

CHOICES_SUBJECT = [
    ('s','استارتاپ'),
    ('c','آموزشی'),
]


class Courses(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200,unique=True)
    description = models.TextField()
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    image = models.ImageField(upload_to = 'courses')
    published = models.BooleanField(default=True)


    class Meta:
        ordering = ('-created',)
        verbose_name = 'دوره آموزشی'
        verbose_name_plural = 'دوره های آموزشی'

    def __str__(self):
        return self.title


class CourseRegister(models.Model):
    course = models.ForeignKey(Courses,on_delete=models.CASCADE,verbose_name='انتخاب دوره')
    name = models.CharField(max_length=100 , verbose_name='نام')
    family = models.CharField(max_length=150, verbose_name='نام خانوادگی')
    father_name = models.CharField(max_length=100, verbose_name='نام پدر')
    meli_code= models.BigIntegerField(verbose_name='کدملی',)
    birthday= models.CharField(max_length=10, verbose_name='تاریخ تولد')
    status = models.CharField(choices=CHOICES,max_length=1, verbose_name='وضعیت تحصیلی')
    reshte = models.CharField(max_length=150, verbose_name='رشته')
    uni_name = models.CharField(max_length=200, verbose_name='نام محل تحصیل')
    phone = models.CharField(max_length=15, verbose_name='تلفن')
    email = models.EmailField(max_length=150, verbose_name='ایمیل')
    city = models.CharField(max_length=100, verbose_name='استان')

    class Meta:
        ordering = ('-name',)
        verbose_name = 'ثبت نام دوره آموزشی'
        verbose_name_plural = 'ثبت نام دوره های آموزشی'
        
    def __str__(self):
        return self.name

class Startup(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200,unique=True)
    description = models.TextField()
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    image = models.ImageField(upload_to = 'startup')
    published = models.BooleanField(default=True)


    class Meta:
        ordering = ('-created',)
        verbose_name = ' استارتاپ'
        verbose_name_plural = 'استارتاپ ها'

    def __str__(self):
        return self.title


class StartupRegister(models.Model):
    how_startup = models.ForeignKey(Startup,on_delete=models.CASCADE,verbose_name='انتخاب استارتاب')
    name = models.CharField(max_length=100 , verbose_name='نام و نام خانوادگی')
    idea_name = models.CharField(max_length=500 , verbose_name='نام ایده')
    idea_description = models.TextField(verbose_name='شرح ایده')
    idea_status = models.CharField(choices=CHOICES_IDEA,max_length=1, verbose_name='وضعیت ثبت ایده')
    zamine = models.TextField(verbose_name='زمينه های تخصصی ايده')
    tarhe_jadid = models.TextField(verbose_name='طرح جدید در پاسخ به چه نیازی بوده و چه مساله ای را حل می‌کند؟')
    maziat_maayeb = models.TextField(verbose_name='مزایا و معایب طرح را شرح دهید')
    zaman_sakht = models.CharField(max_length=500 , verbose_name='پیش بینی تان از زمان و هزینه مورد نیاز جهت نمونه سازی اولیه چقدر است؟')
    manabe = models.TextField(verbose_name='ماخذ علمی یا منابعی را که به توجیه علمی و فنی طرح کمک می کند، نام ببرید')
    khalaqiat = models.TextField (verbose_name='ابتکار، خلاقیت و نوآوری طرح چيست؟')
    group = models.CharField(max_length=1000,verbose_name='اعضای تیم(در صورت وجود)')
    status = models.CharField(choices=CHOICES,max_length=1, verbose_name='وضعیت تحصیلی')
    reshte = models.CharField(max_length=150, verbose_name='رشته تحصیلی')
    uni_name = models.CharField(max_length=200, verbose_name='نام محل تحصیل')
    phone = models.CharField(max_length=15, verbose_name='تلفن')
    email = models.EmailField(max_length=150, verbose_name='ایمیل')
    city = models.CharField(max_length=100, verbose_name='استان')
    

    class Meta:
        ordering = ('-name',)
        verbose_name = 'ثبت نام در استارتاپ'
        verbose_name_plural = 'ثبت نام در استارتاپ ها'
        
    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200,unique=True)
    description = models.TextField()
    text = RichTextUploadingField()
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    image = models.ImageField(upload_to = 'startappnews')
    published = models.BooleanField(default=True)
    subject = models.CharField(choices=CHOICES_SUBJECT,max_length=1,verbose_name='نوع مقاله')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'

    def get_absolute_url(self):
        return reverse('startup:article_detail',args=[self.slug])

    def __str__(self):
        return self.title

startup/views.py
from django.shortcuts import render,get_object_or_404
from .models import CourseRegister,Courses,StartupRegister,Startup,Article
from .form import CourseRegisterForm,StartupRegisterForm
from django.contrib import messages
from blog.models import News

def courses_index(request):
    courses = Courses.objects.filter(published = True)
    all_news = News.objects.filter(published = True)
    all_article = Article.objects.filter(published = True)[:5]
    articles = Article.objects.filter(subject='c')[:5]
    all_course = Courses.objects.filter(published=True)
    return render(request,'startup/courses_index.html',{'courses' : courses,'all_news':all_news,'all_article':all_article,'all_course':all_course,'articles':articles})

def course_register(request):
    all_article = Article.objects.filter(published=True)[:4]
    all_course = Courses.objects.filter(published=True)
    all_news = News.objects.filter(published = True)
    if request.method == 'POST':
        form = CourseRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'ثبت نام شما با موفقیت انجام شد','success')
    else:
        form = CourseRegisterForm()
        messages.error(request,'لطفا اطلاعات خواسته شده را با دقت تکمیل نمایید','danger')
    return render(request,'startup/course_register.html',{'form':form,'all_article':all_article,'all_news':all_news,'all_course':all_course})

def startup_index(request):
    all_startup = Startup.objects.filter(published = True)
    all_course = Courses.objects.filter(published=True)
    all_news = News.objects.filter(published = True)
    all_article = Article.objects.filter(published=True)[:5]
    articles = Article.objects.filter(subject='s')[:5]

    return render(request,'startup/startup_index.html',{'all_startup' : all_startup,'all_news':all_news,'all_article':all_article,'all_course':all_course,'articles':articles})

def startup_register(request):
    all_news = News.objects.filter(published = True)
    all_course = Courses.objects.filter(published=True)
    all_article = Article.objects.filter(published=True)[:5]
    if request.method == 'POST':
        form = StartupRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'ثبت نام شما با موفقیت انجام شد','success')
    else:
        form = StartupRegisterForm()
        messages.error(request,'لطفا اطلاعات خواسته شده را با دقت تکمیل نمایید','danger')
    return render(request,'startup/startup_register.html',{'form':form,'all_news':all_news,'all_article':all_article,'all_course':all_course})

def article_detail(request,slug):
    all_course = Courses.objects.filter(published=True)
    article = get_object_or_404(Article,slug=slug)
    all_news = News.objects.filter(published = True)
    all_article = Article.objects.filter(subject='s')[:5]
    return render(request,'startup/article_detail.html',{'article':article,'all_news':all_news,'all_article':all_article,'all_course':all_course})

def all_article(request):
    all_news = News.objects.filter(published=True)
    all_article = Article.objects.filter(published=True)[:4]
    all_course = Courses.objects.filter(published=True)
    return render(request,'startup/all_article.html',{'all_news':all_news,'all_article' : all_article,'all_course':all_course})

startup/templates/startup/all_article.html
{% extends 'base.html' %}
{% load jformat %}
{% block title %} آرشیو مقالات {% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        {% for article in all_article %}
        <div class="card mb-3">
                <div class="row no-gutters">
                  <div class="col-md-2">
                    <a href="{{ article.get_absolute_url }}"><img src="{{ article.image.url }}" class="img-thumbnail" alt="..."></a>
                  </div>
                  <div class="col-md-10">
                    <div class="card-body">
                      <h5 class="card-title"><a  class="myfonttitle" href="{{ article.get_absolute_url }}">{{ article.title }}</a></h5>
                      <p class="card-text myfontdes">{{ article.description|truncatechars:250 }}</p>
                      <p class="card-text"><small class="myfontnumbers">{{ article.created|jformat:"%Y/%m/%d" }}</small></p>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
        </div>
</div>
{% endblock %}

startup/templates/startup/article_detail.html
{% extends 'base.html' %}
{% load jformat %}
{% block title %} {{ article.title }} {% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron" style="background-color: white;">
          <p class="myfonttitle">{{ article.title }}</p>
          <p class="myfontnumbers">{{ article.created|jformat:"%Y/%m/%d" }}</p>
          <div><img class="img-thumbnail" src="{{ article.image.url }}" alt="{{ article.title }}"></div>
          <p>{{ article.text| safe }}</p>
        </div>
      </div>
    </div>
{% endblock %}

startup/templates/startup/course_register.html
{% extends 'base.html' %}
{% block title %}ثبت نام دوره های آموزشی {% endblock %}
{% block content %}
<div class="row jumbotron myjumbotron">
    <div class="col-md-10">
        <p class="myfonttitle">ثبت نام دوره هاي آموزشی  :</p>
        <br>
        <form action="" method="POST" novalidate>
          {% csrf_token %}
          <div class="col-md-6">
          <span class="registercourses">{{form.as_p}}</span>
          <input type="submit" value="ثبت نام" class="searchbtn">
          </div>
          
        </form>
        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <p {% if message.tags %} class="mymessages"{% endif %}> {{ message }}</p>
              {% endfor %}
          </ul>
        {% endif %}
    </div>
    
</div>
{% endblock %}

startup/templates/startup/courses_index.html
{% extends 'base.html' %}
{% load jformat %}
{% block title %} دوره های آموزشی فعال{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12"><p class="myfonttitle">لیست دوره های آموزشی مرکز</p></div></div>
        {% for cours in courses %}
        <div class="card mb-3" id="mycard">
            <div class="row no-gutters">
                <div class="col-md-2">
                    <img src="{{ cours.image.url }}" class="img-thumbnail" alt="{{ cours.title }}">
                </div>
                <div class="col-md-10">
                    <div class="card-body">
                        <h5 class="myfonttitle">{{ cours.title }}</a></h5>
                        <p class="card-text myfontdes">{{ cours.description|truncatechars:350 }}</p>
                        <p class="card-text"><small class="myfontnumbers">{{ cours.created|jformat:"%Y/%m/%d" }}</small></p>
                        <a class="myfonttitle" href="{% url 'startup:course_register' %}"><input type="submit" name="" id="" value="ثبت نام در دوره" class="btn btn-info"></a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-8"><p class="myfonttitle">مقالات آموزشی</p></div>
            <div class="col-md-4"><a href="{% url 'startup:all_article' %}" class="myfontdes">آرشیو مقالات</a></div></div>
        {% for article in articles %}
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <a href="{{ article.get_absolute_url}}"><img src="{{ article.image.url }}" class="img-thumbnail" alt="..."></a>
                </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title"><a class="myfonttitle" href="{{ article.get_absolute_url}}">{{ article.title }}</a></h5>
                        <p class="card-text"><small class="myfontnumbers">{{ article.created|jformat:"%Y/%m/%d" }}</small></p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

startup/templates/startup/startup_index.html
{% extends 'base.html' %}
{% load jformat %}
{% block title %} استارتاپ های فعال{% endblock %}
{% block content %}
 
<div class="row">
    <div class="col-md-8">
        <div class="row">
            <div class="col-md-12"><p class="myfonttitle">لیست استارتاپ های فعال مرکز</p></div></div>
        {% for startup in all_startup %}
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-2">
                    <a href="#"><img src="{{ startup.image.url }}" class="img-thumbnail" alt="..."></a>
                </div>
                <div class="col-md-10" id="mycard">
                    <div class="card-body">
                        <h5 class="myfonttitle">{{ startup.title }}</a></h5>
                        <p class="card-text myfontdes">{{ startup.description|truncatechars:150 }}</p>
                        <p class="myfontnumbers">{{ startup.created| jformat:"%Y/%m/%d" }}</p>
                        <a class="myfonttitle" href="{% url 'startup:startup_register' %}"><input type="submit" name=""
                                id="" value="ثبت نام در استارتاپ" class="btn btn-info"></a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-12"><p class="myfonttitle">مقالات استارتاپی</p></div>
            <div class="col-md-4"><a href="{% url 'startup:all_article' %}" class="myfontdes">آرشیو مقالات</a></div></div>
        {% for article in articles %}
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <a href="{{ article.get_absolute_url}}"><img src="{{ article.image.url }}" class="img-thumbnail" alt="..."></a>
                </div>
                <div class="col-md-9">
                    <div class="card-body">
                        <h5 class="card-title"><a class="myfonttitle" href="{{ article.get_absolute_url}}">{{ article.title }}</a></h5>
                        <p class="card-text"><small class="myfontnumbers">{{ article.created|jformat:"%Y/%m/%d" }}</small></p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

startup/templates/startup/startup_register.html
{% extends 'base.html' %}
{% block title %}ثبت نام استارتاپ{% endblock %}
{% block content %}
<div class="row jumbotron myjumbotron">

    <div class="col-md-10">
        <p class="myfonttitle">ثبت نام استارتاپ هاي فعال  :</p>
        <br>
        <form action="" method="POST" novalidate>
          {% csrf_token %}
          <div class="col-md-6">
          <span class="registercourses">{{form.as_p}}</span>
          <input type="submit" value="ثبت نام" class="searchbtn">
          </div>
          
        </form>
        {% if messages %}
          <ul class="messages">
              {% for message in messages %}
              <p {% if message.tags %} class="mymessages"{% endif %}> {{ message }}</p>
              {% endfor %}
          </ul>
        {% endif %}
    </div>
    
</div>
{% endblock %}