blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('news/',views.all_news,name ='all_news'),
    path('search/', views.search, name='search'),
    path('',views.index,name='index'),
    path('contact-us/',views.contact_us,name='contact_us'),
    path('about/',views.about,name='about'),
    path('<slug:slug>/',views.news_detail,name='news_detail'),
    
]

myrahkar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('mjs/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('startup-and-courses/',include('startup.urls'),name='startup'),
    path('',include('blog.urls'),name = 'blog'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startup/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='startup'

urlpatterns = [
    path('articles/',views.all_article,name ='all_article'),
    path('courses/',views.courses_index,name='courses_index'),
    path('startup/',views.startup_index,name='startup_index'),
    path('course_register/',views.course_register,name='course_register'),
    path('startup_register/',views.startup_register,name='startup_register'),
    path('<slug:slug>/',views.article_detail,name='article_detail'),
]

blog/models.py
from django.db import models
from django_jalali.db import models as jmodels
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


STATUS_CONTACT=[
    
    ('f','فوری'),
    ('m','معمولی'),
]

class News(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=200,unique=True)
    description = models.TextField()
    text = RichTextUploadingField()
    created = jmodels.jDateTimeField(auto_now_add=True)
    updated = jmodels.jDateTimeField(auto_now=True)
    image = models.ImageField(upload_to = 'news')
    published = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'خبر'
        verbose_name_plural = 'اخبار'

    def get_absolute_url(self):
        return reverse('blog:news_detail',args=[self.slug])

    def __str__(self):
        return self.title


class About(models.Model):

    description = RichTextUploadingField()

    class Meta:
        ordering = ('description',)
        verbose_name = 'درباره'
        verbose_name_plural = 'درباره ما'

    def __str__(self):
        return self.description

class ContactUs(models.Model):
    name = models.CharField(max_length=200,verbose_name='نام و نام خانوادگی')
    email = models.EmailField(max_length=30,verbose_name='ایمیل')
    phone = models.CharField(max_length=20,blank=True,verbose_name='تلفن تماس')
    status = models.CharField(choices=STATUS_CONTACT,max_length=1,verbose_name='میزان اهمیت')
    description = models.TextField(verbose_name='متن درخواست')
    created = jmodels.jDateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)
        verbose_name = 'تماس با ما'
        verbose_name_plural = 'تماس ها'

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from django.forms import ModelForm,Textarea
from .models import ContactUs

class ContactUsForm(ModelForm):
    class Meta:
        model =ContactUs
        fields = '__all__'
        error_messages ={
            'name':{
                'required' :  'لطفا نام خود را وارد نمایید',

            },
            'email':{
                'required' :  'لطفا ایمیل خود را وارد نمایید',

            },
            'status':{
                'required' :  'لطفا میزان اهمیت درخواست خود را مشخص نمایید',

            },
            'description':{
                'required' :  'لطفا متن خود را وارد نمایید',

            },
        }

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'phone': forms.TextInput(attrs={'class':'form-control'}),
            'status': forms.Select(attrs={'class':'form-control registercourses'}),
            'description': forms.Textarea(attrs={'class':'form-control'}),

        }

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import News,About,ContactUs
from startup.models import Article,Courses,Startup
from .forms import ContactUsForm
from django.contrib import messages
from django.views.generic.list import ListView
from django.db.models import Q

def index(request):
    all_news = News.objects.filter(published=True)[:4]
    all_article = Article.objects.filter(published=True)[:4]
    all_startup = Startup.objects.filter(published = True)
    all_course = Courses.objects.filter(published=True)
    return render(request,'blog/index.html',{'all_news':all_news,'all_startup':all_startup,'all_article' : all_article,'all_course':all_course})

def about(request):
    all_news = News.objects.filter(published=True)[:4]
    all_article = Article.objects.filter(published=True)[:4]
    all_course = Courses.objects.filter(published=True)
    about = About.objects.all()
    return render(request,'blog/about.html',{'all_news':all_news,'all_article' : all_article,'all_course':all_course,'about':about})

def contact_us(request):
    all_news = News.objects.filter(published=True)[:4]
    all_article = Article.objects.filter(published=True)[:4]
    all_course = Courses.objects.filter(published=True)
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'درخواست شما با موفقیت ارسال شد','success')
    else:
        form = ContactUsForm()
        messages.error(request,'لطفا اطلاعات خواسته شده را با دقت تکمیل نمایید','danger')
    return render(request,'blog/contact_us.html',{'all_news':all_news,'all_article' : all_article,'all_course':all_course,'form':form})

def news_detail(request,slug):
    all_news = News.objects.filter(published=True)[:4]
    news = get_object_or_404(News,slug=slug)
    all_article = Article.objects.filter(published=True)[:4]
    all_course = Courses.objects.filter(published=True)
    return render(request,'blog/news_detail.html',{'news':news,'all_article' : all_article,'all_news':all_news,'all_course':all_course})

def all_news(request):
    all_news = News.objects.filter(published=True)
    all_article = Article.objects.filter(published=True)[:4]
    all_course = Courses.objects.filter(published=True)
    return render(request,'blog/all_news.html',{'all_news':all_news,'all_article' : all_article,'all_course':all_course})

def search(request):
        all_news = News.objects.filter(published=True)
        all_article = Article.objects.filter(published=True)[:4]
        all_course = Courses.objects.filter(published=True)
        if request.method == 'GET':
            query = request.GET.get('q')
            object_list = News.objects.filter(
                Q(title__icontains=query)|Q(text__icontains=query)
            )
        return render(request,'blog/search.html',{'all_news':all_news,'all_article' : all_article,'all_course':all_course,'object_list':object_list})

blog/templates/blog/about.html
{% extends 'base.html' %}
{% block title %} درباره ما {% endblock %}
{% block content %}
<div class=" row jumbotron myjumbotron">
    {{ about|safe }}
</div>
{% endblock %}

blog/templates/blog/all_news.html
{% extends 'base.html' %}
{% load jformat %}
{% block title %} آرشیو اخبار {% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        {% for news in all_news %}
        <div class="card mb-3">
                <div class="row no-gutters">
                  <div class="col-md-2">
                    <a href="{{ news.get_absolute_url }}"><img src="{{ news.image.url }}" class="img-thumbnail" alt="..."></a>
                  </div>
                  <div class="col-md-10">
                    <div class="card-body">
                      <h5 class="card-title"><a  class="myfonttitle" href="{{ news.get_absolute_url }}">{{ news.title }}</a></h5>
                      <p class="card-text myfontdes">{{ news.description|truncatechars:150 }}</p>
                      <p class="card-text"><small class="myfontnumbers">{{ news.created|jformat:"%Y/%m/%d" }}</small></p>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
        </div>
</div>
{% endblock %}

blog/templates/blog/contact_us.html
{% extends 'base.html' %}
{% block title %} تماس با ما {% endblock %}
{% block content %}
<div class=" row jumbotron myjumbotron">
    <div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <p {% if message.tags %} class="mymessages" {% endif %}> {{ message }}</p>
            {% endfor %}
        </ul>

        {% endif %}
        <br>
        <form action="" method="POST" novalidate>
            {% csrf_token %}
            <span class="registercourses">{{ form.as_p }}</span>
            <br>
            <input type="submit" class="searchbtn" value="ارسال" id="">
        </form>
    </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}
{% load jformat %}
{% block content %}
<div class="row">
    <div class="col-sm-8">
        {% for news in all_news %}
        <div class="card mb-3" id="mycard">
                <div class="row no-gutters">
                  <div class="col-md-2">
                    <a href="{{ news.get_absolute_url }}"><img src="{{ news.image.url }}" class="img-thumbnail" alt="..."></a>
                  </div>
                  <div class="col-md-10">
                    <div class="card-body">
                      <h5 class="card-title"><a  class="myfonttitle" href="{{ news.get_absolute_url }}">{{ news.title }}</a></h5>
                      <p class="card-text myfontdes">{{ news.description|truncatechars:150 }}</p>
                      <p class="card-text"><small class="myfontnumbers">{{ news.created|jformat:"%Y/%m/%d %H:%M"  }}</small></p>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
        </div>
    <div class="col-sm-4">
      <div>
        <form action="{% url 'blog:search' %}" method="GET" >
          <div class="input-group">
          <input id="" name="q" class="form-control myfontdes" type="text" placeholder="عنوان مورد نظر خود را وارد نمایید..." name="search">
          <div class="input-group-btn">
          <input type="submit" class="searchbtn form-control" value="جستجو"></button>
          </div>
        </div>
        </form>
      </div>
      <div>
        <img class="bannerleftindex" src="{% static '/img/1584677412-99.jpg' %}" alt="سال جهش تولید">
        <br>
        <img class="bannerleftindex" src="{% static '/img/9904-ACECR-40th.jpg' %}" alt="چهل ساد حودباوری با جهاددانشگاهی">
      </div>
      <div class="card mb-3">
        <div>
          <p class="mefontnew" ">ثبت نام دوره های آموزشی</p>
        </div>
        <hr class="myhr">
        <ul>
          <a href="{% url 'startup:courses_index' %}"><img class="bannerregister" src="{% static '/img/register.png' %}" alt="ثبت نام دوره ها"></a>
        </ul> 
      </div>
      <div class="card mb-3">
        <div>
          <p class="mefontnew">استارتاپ های فعال مرکز </p>
        </div>
        <hr class="myhr">
          {% for startup in all_startup %}
              <div class="row no-gutters" id="startupindex">
                  <div class="col-md-4">
                      <a href="{% url 'startup:startup_index' %}"><img src="{{ startup.image.url }}" class="img-thumbnail" alt="..."></a>
                  </div>
                  <div class="col-md-8">
                      <div class="card-body">
                          <small class="card-title"><a href="{% url 'startup:startup_index' %}">{{ startup.title }}</a></small>
                          
                      </div>
                  </div>
              </div>
              {% endfor %}
          </div>
          
        <div class="card mb-3">
          <div>
            <p class="mefontnew">نوشته های تازه</p>
          </div>
          <hr class="myhr">
          <ul>
            {% for news in all_news %}
            <li><a class="myfontdes" href="{{ news.get_absolute_url }}">{{ news.title }}</a></li>
            {% endfor %}
          </ul> 
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/news_detail.html
{% extends 'base.html' %}
{% load jformat %}
{% block title %} {{ news.title }} {% endblock %}
{% block content %}
    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron" style="background-color: white;">
          <p class="myfonttitle">{{ news.title }}</p>
          <p class="myfontnumbers">{{ news.created|jformat:"%Y/%m/%d %H:%M" }}</p>
          <div><img class="img-thumbnail" src="{{ news.image.url }}" alt="{{ news.title }}" ></div>
          <p>{{ news.text|safe }}</p>
        </div>
      </div>
    </div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'base.html' %}
{% load jformat %}
{% block content %}
<p class="myfonttitle">نتایج جستجو</p>
<br>


  {% for news in object_list %}
        <div class="card mb-3" id="mycard">
            <div class="row no-gutters">
              <div class="col-md-2">
                <a href="{{ news.get_absolute_url }}"><img src="{{ news.image.url }}" class="img-thumbnail" alt="..."></a>
              </div>
              <div class="col-md-10">
                <div class="card-body">
                  <h5 class="card-title"><a  class="myfonttitle" href="{{ news.get_absolute_url }}">{{ news.title }}</a></h5>
                  <p class="card-text myfontdes">{{ news.description|truncatechars:150 }}</p>
                  <p class="card-text"><small class="myfontnumbers">{{ news.created|jformat:"%Y/%m/%d %H:%M"  }}</small></p>
                </div>
              </div>
            </div>
          </div>
  {% endfor %}
{% endblock %}