blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('news/',views.all_news,name ='all_news'),
    path('search/', views.search, name='search'),
    path('',views.index,name='index'),
    path('contact-us/',views.contact_us,name='contact_us'),
    path('about/',views.about,name='about'),
    path('<slug:slug>/',views.news_detail,name='news_detail'),
    
]

myrahkar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('mjs/', admin.site.urls),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('startup-and-courses/',include('startup.urls'),name='startup'),
    path('',include('blog.urls'),name = 'blog'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startup/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='startup'

urlpatterns = [
    path('articles/',views.all_article,name ='all_article'),
    path('courses/',views.courses_index,name='courses_index'),
    path('startup/',views.startup_index,name='startup_index'),
    path('course_register/',views.course_register,name='course_register'),
    path('startup_register/',views.startup_register,name='startup_register'),
    path('<slug:slug>/',views.article_detail,name='article_detail'),
]

templates/inc/copyright.html
<div class="copyrightdiv" dir="rtl">© کلیه حقوق متعلق به دفترکارآفرینی مرکز علمی کاربردی جهاددانشگاهی کرمانشاه می باشد، انتشار مطالب با ذکر منبع بلامانع می باشد. </div>

templates/inc/footer.html
<div class="jumbotron myfooter">
    <div class="row">
        <div class="col-md-4">
            <div class="row">
                <p class="myfootertitle">نوشته های تازه</p>
            </div>
            <hr  class="hrfooter">
            <div class="row">
                <ul>
                    {% for news in all_news %}
                    <li><a class="footerfont" href="{{ news.get_absolute_url }}">{{ news.title }}</a></li>
                    {% endfor %}
                  </ul> 
            </div>
        </div>
        <div class="col-md-4">
            <div class="row">
                <p class="myfootertitle">آخرین مقالات</p>
            </div>
            <hr  class="hrfooter">
            <div class="row">
                <ul>
                    {% for article in all_article %}
                    <li><a class="footerfont" href="{{ article.get_absolute_url }}">{{ article.title }}</a></li>
                    {% endfor %}
                  </ul> 
            </div>           
        </div>
        <div class="col-md-4">
            <div class="row">
                <p class="myfootertitle">دوره های آموزشی فعال</p>
            </div>
            <hr  class="hrfooter">
            <div class="row">
                <ul>
                    {% for course in all_course %}
                    <li><a class="footerfont" href="{% url 'startup:courses_index' %}">{{ course.title }}</a></li>
                    {% endfor %}
                  </ul> 
            </div>       
        </div>
    </div>
</div>

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light mynavbar">
    <a class="navbar-brand" href="{% url 'blog:index' %}">راهکار</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog:index' %}">صفحه اصلی <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" href="{% url 'blog:all_news' %}">اخبار</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" href="{% url 'startup:all_article' %}">مقالات</a>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="{% url 'startup:courses_index' %}">دوره ها</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'startup:startup_index' %}">استارتاپ ها</a>
      </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:contact_us' %}">تماس با ما</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'blog:about' %}">درباره ما</a>
        </li>
      </ul>
    </div>
</nav>